name: Super-Linter

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7.1.0
        env:
          env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Only check changed files
  VALIDATE_ALL_CODEBASE: false

  # Disable strict/annoying checks
  VALIDATE_PYTHON_PYLINT: false
  VALIDATE_PYTHON_MYPY: false
  VALIDATE_PYTHON_ISORT: false
  VALIDATE_JSCPD: false
  VALIDATE_NATURAL_LANGUAGE: false
  VALIDATE_HTML: false
  VALIDATE_MARKDOWN: false